Program EncontraMaior;

Var
    nome1, nome2, nome3: string[10];
    idade1, idade2, idade3: integer;
Begin
    readln(nome1);
    readln(idade1);
    readln(nome2);
    readln(idade2);
    readln(nome3);
    readln(idade3);
    if(idade1>idade2)and(idade2>idade3)then
    begin
        writeln(nome1);
        writeln(idade1);
        writeln(nome3);
        writeln(idade3);
    end
    else
    begin
        if(idade1>idade3)and(idade3>idade2)then
        begin
            writeln(nome1);
            writeln(idade1);
            writeln(nome2);
            writeln(idade2);
        end
        else
        begin
            if(idade2>idade1)and(idade1>idade3)then
            begin
                writeln(nome2);
                writeln(idade2);
                writeln(nome3);
                writeln(idade3);
            end
            else
            begin
                if(idade2>idade3)and(idade3>idade1)then
                begin
                    writeln(nome2);
                    writeln(idade2);
                    writeln(nome1);
                    writeln(idade1);
                end
                else
                begin
                    if(idade3>idade1)and(idade3>idade2)then
                    begin
                        writeln(nome3);
                        writeln(idade3);
                        writeln(nome2);
                        writeln(idade2);
                    end
                    else
                    begin
                        writeln(nome3);
                        writeln(idade3);
                        writeln(nome1);
                        writeln(idade1);
                    end;
                end;
            end;
        end;
    end;
End.
