/*
 * Entradas.java
 *
 * Created on 15 de Setembro de 2007, 21:09
 */

package gui;

import java.awt.Color;
import java.io.File;
import java.io.IOException;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import log.GerenciaIO;
import src.Aluno;
import src.Arquivos;
import src.ListaIO;
import src.PastaCorrecao;

/**
 *
 * @author  UltraXP
 */
public class IO extends javax.swing.JDialog {
    
    PastaCorrecao[] pastasCorrecao = null;
    File diretorio = null;
    
    /** Creates new form Entradas */
    public IO(java.awt.Frame parent, File diretorio, PastaCorrecao[] pastasCorrecao) {
        super(parent, true);
        this.pastasCorrecao = pastasCorrecao;
        this.diretorio = diretorio;
        initComponents();
        Janelas.alinharContainer(this);
        mudarCorEditor(0);
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Cï¿½digo Gerado ">//GEN-BEGIN:initComponents
    private void initComponents() {
        btnCancelar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        listaEntradas = new javax.swing.JList();
        btnAdicionar = new javax.swing.JButton();
        btnRemover = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnSalvar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtGabarito = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtEntrada = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        listaCorrecoes = new javax.swing.JList();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Entradas e Gabaritos");
        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        listaEntradas.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                listaEntradasValueChanged(evt);
            }
        });

        jScrollPane1.setViewportView(listaEntradas);

        btnAdicionar.setText("Adicionar");
        btnAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdicionarActionPerformed(evt);
            }
        });

        btnRemover.setText("Remover");
        btnRemover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoverActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel1.setText("Entrada");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel2.setText("Gabarito");

        btnSalvar.setText("Salvar Altera\u00e7\u00f5es");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        txtGabarito.setColumns(20);
        txtGabarito.setRows(5);
        jScrollPane2.setViewportView(txtGabarito);

        txtEntrada.setColumns(20);
        txtEntrada.setRows(5);
        jScrollPane3.setViewportView(txtEntrada);

        listaCorrecoes.setListData(getCorrecoes());
        listaCorrecoes.setSelectedIndex(0);
        atualizarListaIO();
        listaCorrecoes.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                listaCorrecoesValueChanged(evt);
            }
        });

        jScrollPane4.setViewportView(listaCorrecoes);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(jScrollPane4, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 116, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(layout.createSequentialGroup()
                                .add(btnRemover, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED))
                            .add(org.jdesktop.layout.GroupLayout.TRAILING, btnAdicionar))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jLabel1)
                            .add(jScrollPane3, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 261, Short.MAX_VALUE))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jLabel2)
                            .add(jScrollPane2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 261, Short.MAX_VALUE)))
                    .add(layout.createSequentialGroup()
                        .add(btnCancelar)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 646, Short.MAX_VALUE)
                        .add(btnSalvar)))
                .addContainerGap())
        );

        layout.linkSize(new java.awt.Component[] {btnAdicionar, btnRemover, jScrollPane1}, org.jdesktop.layout.GroupLayout.HORIZONTAL);

        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel1)
                    .add(jLabel2))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jScrollPane2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 212, Short.MAX_VALUE)
                    .add(jScrollPane3, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 212, Short.MAX_VALUE)
                    .add(layout.createSequentialGroup()
                        .add(btnAdicionar)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(btnRemover))
                    .add(jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 212, Short.MAX_VALUE)
                    .add(jScrollPane4, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 212, Short.MAX_VALUE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(btnCancelar)
                    .add(btnSalvar))
                .addContainerGap())
        );
        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRemoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoverActionPerformed
        GerenciaIO gerencia = new GerenciaIO(pastasCorrecao[listaCorrecoes.getSelectedIndex()]);
        gerencia.removerIO(listaEntradas.getSelectedIndex());
        atualizarListaIO();
    }//GEN-LAST:event_btnRemoverActionPerformed

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        ListaIO listaIO = pastasCorrecao[listaCorrecoes.getSelectedIndex()].getListaIO();
        
        listaIO.alterarIO(listaEntradas.getSelectedIndex(), txtEntrada.getText(), txtGabarito.getText());
        Arquivos.serializarCorrecao(diretorio, pastasCorrecao);
        JOptionPane.showMessageDialog(null, "Alterações salvas com sucesso!", "Sucesso!", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void listaEntradasValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_listaEntradasValueChanged
        String entrada = pastasCorrecao[listaCorrecoes.getSelectedIndex()].getListaIO().getEntrada(listaEntradas.getSelectedIndex());
        String gabarito = pastasCorrecao[listaCorrecoes.getSelectedIndex()].getListaIO().getGabarito(listaEntradas.getSelectedIndex());
        
        if (entrada != null) {
            mudarCorEditor(1);
            txtEntrada.setText(entrada);
            txtGabarito.setText(gabarito);
        }
    }//GEN-LAST:event_listaEntradasValueChanged

    private void btnAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdicionarActionPerformed
        int indice = listaCorrecoes.getSelectedIndex();
        GerenciaIO gerIO = new GerenciaIO(pastasCorrecao[indice]);
        gerIO.adicionar();
        atualizarListaIO();
    }//GEN-LAST:event_btnAdicionarActionPerformed

    private void listaCorrecoesValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_listaCorrecoesValueChanged
        atualizarListaIO();
        mudarCorEditor(0);
    }//GEN-LAST:event_listaCorrecoesValueChanged

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void mudarCorEditor(int modo) {
        if (modo == 0) {
            txtEntrada.setBackground(Color.LIGHT_GRAY);
            txtGabarito.setBackground(Color.LIGHT_GRAY);
            txtEntrada.setEnabled(false);
            txtGabarito.setEnabled(false);
        } else if (modo == 1) {
            txtEntrada.setBackground(Color.WHITE);
            txtGabarito.setBackground(Color.WHITE);
            txtEntrada.setEnabled(true);
            txtGabarito.setEnabled(true);
        }
    }
    
    private String[] getCorrecoes() {
        String[] nomesCorrecoes = new String[pastasCorrecao.length];
        for (int i = 0; i <= pastasCorrecao.length - 1; i++) {
            nomesCorrecoes[i] = pastasCorrecao[i].getPasta().getName();
        }
        
        return nomesCorrecoes;
    }
    
    private void atualizarListaIO() {
        txtEntrada.setText("");
        txtGabarito.setText("");
        GerenciaIO gerencia = new GerenciaIO(pastasCorrecao[listaCorrecoes.getSelectedIndex()]);
        listaEntradas.setListData(gerencia.getVetorIO());
    }
    
    
    // Declaraï¿½ï¿½o de variï¿½veis - nï¿½o modifique//GEN-BEGIN:variables
    private javax.swing.JButton btnAdicionar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnRemover;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JList listaCorrecoes;
    private javax.swing.JList listaEntradas;
    private javax.swing.JTextArea txtEntrada;
    private javax.swing.JTextArea txtGabarito;
    // Fim da declaraï¿½ï¿½o de variï¿½veis//GEN-END:variables
    
}
