/*
 * BarraProgresso.java
 *
 * Created on 18 de Setembro de 2007, 00:52
 */

package gui;

import javax.swing.JProgressBar;

/**
 *
 * @author  UltraXP
 */
public class BarraProgresso extends javax.swing.JDialog {
    
    /** Creates new form BarraProgresso */
    public BarraProgresso(java.awt.Frame parent) {
        super(parent, true);
        initComponents();
        setTitle("Carregando...");
        barraProgresso.setMinimum(0);  
        barraProgresso.setMaximum(100);  
        barraProgresso.setIndeterminate(false);
        barraProgresso.setStringPainted(true);
        barraProgresso.setValue(0);
        Janelas.alinharContainer(this);
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Código Gerado ">//GEN-BEGIN:initComponents
    private void initComponents() {
        barraProgresso = new javax.swing.JProgressBar();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(barraProgresso, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 308, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(barraProgresso, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
        );
        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    public JProgressBar getBarraProgresso() {
        return barraProgresso;
    }
    
    // Declaração de variáveis - não modifique//GEN-BEGIN:variables
    private javax.swing.JProgressBar barraProgresso;
    // Fim da declaração de variáveis//GEN-END:variables
    
}
