/*
 * BarraProgresso.java
 *
 * Created on 4 de Dezembro de 2007, 17:01
 */

package gui;

import java.awt.Toolkit;
import java.beans.PropertyChangeEvent;
import java.beans.PropertyChangeListener;
import java.util.Random;
import javax.swing.JFrame;
import javax.swing.JProgressBar;
import javax.swing.SwingWorker;

/**
 *
 * @author  UltraXP
 */
public class BarraProgresso extends javax.swing.JDialog implements PropertyChangeListener {
    
    private Task task;
    
    class Task extends SwingWorker<Void, Void> {
        /*
         * Main task. Executed in background thread.
         */
        public Void doInBackground() {
            Random random = new Random();
            int progress = 0;
            //Initialize progress property.
            setProgress(0);
            while (progress < 100) {
                //Sleep for up to one second.
                try {
                    Thread.sleep(random.nextInt(1000));
                } catch (InterruptedException ignore) {}
                //Make random progress.
                progress += random.nextInt(10);
                setProgress(Math.min(progress, 100));
            }
            return null;
        }

        /*
         * Executed in event dispatching thread
          */
        public void done() {
            Toolkit.getDefaultToolkit().beep();
            setCursor(null); //turn off the wait cursor
            //taskOutput.append("Done!\n");
        }
    }
    
    /** Creates new form BarraProgresso */
    public BarraProgresso() {
        super(new JFrame(), true);
        initComponents();
        /*rect = barraProgresso.getBounds();
        barraProgresso.setBounds(rect);
        barraProgresso.setMinimum(1);
        barraProgresso.setMaximum(100);
        barraProgresso.setIndeterminate(true);
        barraProgresso.setStringPainted(true);
        barraProgresso.setValue(1);*/
        //Create the demo's UI.

        barraProgresso = new JProgressBar(0, 100);
        barraProgresso.setValue(0);
        barraProgresso.setStringPainted(true);
        Janelas.alinharContainer(this);
        this.pack();
        this.setVisible(true);
        task.execute();
    }
    
    /**
     * Invoked when task's progress property changes.
     */
    public void propertyChange(PropertyChangeEvent evt) {
        if ("progress" == evt.getPropertyName()) {
            int progress = (Integer) evt.getNewValue();
            barraProgresso.setValue(progress);
            /*taskOutput.append(String.format(
                    "Completed %d%% of task.\n", task.getProgress()));*/
        } 
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Código Gerado ">//GEN-BEGIN:initComponents
    private void initComponents() {
        barraProgresso = new javax.swing.JProgressBar();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        barraProgresso.setMaximumSize(new java.awt.Dimension(32767, 20));
        barraProgresso.setMinimumSize(new java.awt.Dimension(10, 20));
        barraProgresso.setPreferredSize(new java.awt.Dimension(100, 20));

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(barraProgresso, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 253, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(barraProgresso, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
        );
        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    // Declaração de variáveis - não modifique//GEN-BEGIN:variables
    private javax.swing.JProgressBar barraProgresso;
    // Fim da declaração de variáveis//GEN-END:variables
    
}
