package gui;

/**
 *
 * @author  UltraXP
 */
public class Principal extends javax.swing.JFrame {
    
    /** Creates new form Principal */
    public Principal() {
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Código Gerado ">//GEN-BEGIN:initComponents
    private void initComponents() {
        jMenuBar1 = new javax.swing.JMenuBar();
        menuArquivo = new javax.swing.JMenu();
        itemNova = new javax.swing.JMenuItem();
        itemImportar = new javax.swing.JMenuItem();
        itemSair = new javax.swing.JMenuItem();
        menuFerramentas = new javax.swing.JMenu();
        itemEntradas = new javax.swing.JMenuItem();
        itemGabaritos = new javax.swing.JMenuItem();
        itemAnotacoes = new javax.swing.JMenuItem();
        itemRelatorio = new javax.swing.JMenuItem();
        menuAjuda = new javax.swing.JMenu();
        itemAjuda = new javax.swing.JMenuItem();
        itemSobre = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        menuArquivo.setText("Arquivo");
        itemNova.setText("Nova Corre\u00e7\u00e3o");
        menuArquivo.add(itemNova);

        itemImportar.setText("Importar Corre\u00e7\u00e3o...");
        menuArquivo.add(itemImportar);

        itemSair.setText("Sair");
        menuArquivo.add(itemSair);

        jMenuBar1.add(menuArquivo);

        menuFerramentas.setText("Ferramentas");
        itemEntradas.setText("Editar Entradas");
        itemEntradas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemEntradasActionPerformed(evt);
            }
        });

        menuFerramentas.add(itemEntradas);

        itemGabaritos.setText("Editar Gabaritos");
        menuFerramentas.add(itemGabaritos);

        itemAnotacoes.setText("Anota\u00e7\u00f5es");
        menuFerramentas.add(itemAnotacoes);

        itemRelatorio.setText("Gerar Relat\u00f3rio de Anota\u00e7\u00f5es");
        menuFerramentas.add(itemRelatorio);

        jMenuBar1.add(menuFerramentas);

        menuAjuda.setText("Ajuda");
        itemAjuda.setText("Conte\u00fados de Ajuda");
        menuAjuda.add(itemAjuda);

        itemSobre.setText("Sobre");
        menuAjuda.add(itemSobre);

        jMenuBar1.add(menuAjuda);

        setJMenuBar(jMenuBar1);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 279, Short.MAX_VALUE)
        );
        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void itemEntradasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemEntradasActionPerformed
// TODO adicione seu código de manipulação aqui:
    }//GEN-LAST:event_itemEntradasActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }
    
    // Declaração de variáveis - não modifique//GEN-BEGIN:variables
    private javax.swing.JMenuItem itemAjuda;
    private javax.swing.JMenuItem itemAnotacoes;
    private javax.swing.JMenuItem itemEntradas;
    private javax.swing.JMenuItem itemGabaritos;
    private javax.swing.JMenuItem itemImportar;
    private javax.swing.JMenuItem itemNova;
    private javax.swing.JMenuItem itemRelatorio;
    private javax.swing.JMenuItem itemSair;
    private javax.swing.JMenuItem itemSobre;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu menuAjuda;
    private javax.swing.JMenu menuArquivo;
    private javax.swing.JMenu menuFerramentas;
    // Fim da declaração de variáveis//GEN-END:variables
    
}
