/*
 * Relatorio.java
 *
 * Created on 1 de Dezembro de 2007, 19:52
 */

package gui;

import javax.swing.DefaultComboBoxModel;
import javax.swing.JFrame;
import src.Aluno;
import src.PastaCorrecao;
import src.Saidas;

/**
 *
 * @author  UltraXP
 */
public class Relatorio extends javax.swing.JDialog {
    
    private PastaCorrecao pastaCorrecao = null;
    private Aluno aluno;
    
    /** Creates new form Relatorio */
    public Relatorio(PastaCorrecao pastaCorrecao, int alunoSelecionado, String titulo, JFrame pai) {
        super(pai, titulo, true);
        this.pastaCorrecao = pastaCorrecao;
        this.aluno = pastaCorrecao.getAlunos()[alunoSelecionado];
        initComponents();
        Janelas.alinharContainer(this);
        iniciarCombos();
    }
    
    private void iniciarCombos() {
        int nroQuestoes = pastaCorrecao.getArrayListIO().size();
        int nroTestes1 = pastaCorrecao.getArrayListIO().get(0).getTamLista();
        String[] vetorQuestao = new String[nroQuestoes];
        String[] vetorTestes1 = new String[nroTestes1];
        
        for (int i = 0; i <= nroQuestoes - 1; i++) {
            vetorQuestao[i] = "Questão " + (i + 1);
        }
        DefaultComboBoxModel modelQuestao = new DefaultComboBoxModel(vetorQuestao);
        
        for (int i = 0; i <= nroTestes1 - 1; i++) {
            vetorTestes1[i] = "Teste " + (i + 1);
        }
        
        DefaultComboBoxModel modelTeste1 = new DefaultComboBoxModel(vetorTestes1);
        
        cmbQuestao.setModel(modelQuestao);
        cmbTeste.setModel(modelTeste1);
        
        cmbQuestao.setSelectedIndex(0);
        Saidas saidas = aluno.getFontes()[0].getSaidas().get(0);
        cmbTeste.setSelectedIndex(0);
        txtSaida.setText(saidas.getSaida());
        txtRelatorio.setText(saidas.getRelatorio());
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Código Gerado ">//GEN-BEGIN:initComponents
    private void initComponents() {
        btnVoltar = new javax.swing.JButton();
        cmbTeste = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        cmbQuestao = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtSaida = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtRelatorio = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        btnVoltar.setText("Voltar");
        btnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarActionPerformed(evt);
            }
        });

        cmbTeste.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbTesteActionPerformed(evt);
            }
        });

        jLabel2.setText("N\u00famero do Teste");

        cmbQuestao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbQuestaoActionPerformed(evt);
            }
        });

        jLabel3.setText("N\u00famero da Quest\u00e3o");

        txtSaida.setColumns(20);
        txtSaida.setEditable(false);
        txtSaida.setRows(5);
        jScrollPane1.setViewportView(txtSaida);

        jLabel1.setText("Sa\u00edda do Programa");

        txtRelatorio.setColumns(20);
        txtRelatorio.setEditable(false);
        txtRelatorio.setRows(5);
        jScrollPane2.setViewportView(txtRelatorio);

        jLabel4.setText("Relat\u00f3rio");

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(btnVoltar)
                    .add(layout.createSequentialGroup()
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                            .add(org.jdesktop.layout.GroupLayout.LEADING, layout.createSequentialGroup()
                                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(jLabel3)
                                    .add(layout.createSequentialGroup()
                                        .add(10, 10, 10)
                                        .add(jLabel2)))
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                                    .add(cmbQuestao, 0, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .add(cmbTeste, 0, 85, Short.MAX_VALUE)))
                            .add(org.jdesktop.layout.GroupLayout.LEADING, jLabel1)
                            .add(org.jdesktop.layout.GroupLayout.LEADING, jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 267, Short.MAX_VALUE))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                            .add(layout.createSequentialGroup()
                                .add(jLabel4)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 272, Short.MAX_VALUE))
                            .add(jScrollPane2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 315, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel3)
                    .add(cmbQuestao, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel2)
                    .add(cmbTeste, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel1)
                    .add(jLabel4))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 252, Short.MAX_VALUE)
                    .add(jScrollPane2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 252, Short.MAX_VALUE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(btnVoltar)
                .addContainerGap())
        );
        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmbTesteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbTesteActionPerformed
        Saidas saidas = aluno.getFontes()[cmbQuestao.getSelectedIndex()].getSaidas().get(cmbTeste.getSelectedIndex());
        txtSaida.setText(saidas.getSaida());
        txtRelatorio.setText(saidas.getRelatorio());
    }//GEN-LAST:event_cmbTesteActionPerformed

    private void cmbQuestaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbQuestaoActionPerformed
        int nroTestes = pastaCorrecao.getArrayListIO().get(cmbQuestao.getSelectedIndex()).getTamLista();
        String[] vetorTestes = new String[nroTestes];
        
        for (int i = 0; i <= nroTestes - 1; i++) {
            vetorTestes[i] = "Teste " + (i + 1);
        }
        
        DefaultComboBoxModel modelTeste = new DefaultComboBoxModel(vetorTestes);
        cmbTeste.setModel(modelTeste);
        
        Saidas saidas = aluno.getFontes()[cmbQuestao.getSelectedIndex()].getSaidas().get(0);
        cmbTeste.setSelectedIndex(0);
        txtSaida.setText(saidas.getSaida());
        txtRelatorio.setText(saidas.getRelatorio());
    }//GEN-LAST:event_cmbQuestaoActionPerformed

    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarActionPerformed
    this.dispose();
    }//GEN-LAST:event_btnVoltarActionPerformed
 
   
    // Declaração de variáveis - não modifique//GEN-BEGIN:variables
    private javax.swing.JButton btnVoltar;
    private javax.swing.JComboBox cmbQuestao;
    private javax.swing.JComboBox cmbTeste;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea txtRelatorio;
    private javax.swing.JTextArea txtSaida;
    // Fim da declaração de variáveis//GEN-END:variables
    
}
